// Generated by BUCKLESCRIPT VERSION 2.0.1, PLEASE EDIT WITH CARE
'use strict';

var Block  = require("bs-platform/lib/js/block.js");
var Printf = require("bs-platform/lib/js/printf.js");

Printf.printf(/* Format */[
      /* String_literal */Block.__(11, [
          "Hello world",
          /* End_of_format */0
        ]),
      "Hello world"
    ]);

/*  Not a pure module */
